name: draft_builder
description: The build runner for the draft package.
version: 0.0.6
repository: https://github.com/josiahsrc/draft

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.1.1
  build: ^3.0.2
  source_gen: ^4.0.0
  draft: ^0.0.12

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_test: ^3.3.2
  build_runner: ^2.3.3
